"""
Configuration for faster-whisper-backend.

Edit the values in this file to tune the deployment. Each setting can ALSO
be overridden at runtime via a matching WHISPER_* environment variable (set
on the Windows Service via <env> elements in WhisperAPI.xml, generated by
install-service.ps1). The env var wins over the value here, so this file
holds the in-repo defaults and env vars hold per-machine overrides.

Conventions:
- Module attribute names are UPPER_CASE.
- Public symbols (no leading underscore) are intended to be edited.
- Algorithm code (regex compilation, pipeline functions) lives in main.py.
"""
import os


# =============================================================================
# Models
# =============================================================================

# Model loaded when a client sends `model="whisper-1"` (OpenAI default) or
# omits the field. Any faster-whisper short name or full HF repo id works.
# Examples:
#   "large-v2", "large-v3", "large-v3-turbo", "distil-large-v3"
#   "Systran/faster-whisper-large-v3"
#   "GalaktischeGurke/primeline-whisper-large-v3-german-ct2"
DEFAULT_MODEL = "large-v2"

# Restrict which models clients are allowed to load. An empty set means "any
# model name passes through" — convenient on a private LAN, but lets a client
# trigger a multi-GB download by sending an unknown name. Add entries to
# enforce a known list. Curated CH-DE / German starter set; uncomment to
# enable.
ALLOWED_MODELS: "set[str]" = {
    "large-v2",
    "large-v3",
    "GalaktischeGurke/primeline-whisper-large-v3-german-ct2",
    # --- Systran's official faster-whisper builds (auto-resolved from HF) ---
    # "large-v2",
    # "large-v3",
    # "large-v3-turbo",         # ~4x faster than large-v3, slight quality dip
    # "distil-large-v3",        # smaller; English-leaning, may regress on CH-DE

    # --- German-finetuned, pre-converted to CTranslate2 ----------------------
    # "GalaktischeGurke/primeline-whisper-large-v3-german-ct2",
    # "conkhidan/primeline-whisper-large-v3-turbo-german-ct2",
}

# Number of models to keep hot in VRAM. LRU eviction beyond this. Each
# large-v3 model is ~1.5 GB on float16 CUDA; turbo/distill variants are
# ~600 MB. Pick based on free VRAM after the OS / other apps.
MAX_LOADED_MODELS = 3

# Time-based eviction: unload a model after this many seconds without
# being used (touched on every transcribe). 0 disables time-based
# eviction (current behavior — only LRU-evict when MAX_LOADED_MODELS
# is exceeded). Common values: 1800 (30 min), 3600 (1 h), 14400 (4 h).
MODEL_IDLE_TIMEOUT_S = 0

# Models to load eagerly at server startup. Listed models stay hot in VRAM
# from boot, so the first request to each doesn't pay the 5-30 s warm-up.
# If empty, only DEFAULT_MODEL is preloaded (current/historical behavior).
# Keep len(PRELOAD_MODELS) <= MAX_LOADED_MODELS or LRU eviction starts
# fighting your own preloads. Order doesn't matter for behavior, only for
# load order at startup.
PRELOAD_MODELS: "list[str]" = [
    "large-v2",
    "large-v3",
    "GalaktischeGurke/primeline-whisper-large-v3-german-ct2",
]

# Primary load device + precision. CUDA + float16 is the GPU path.
MODEL_DEVICE = "cuda"
MODEL_COMPUTE_TYPE = "float16"

# Fallback if the primary load fails (e.g. CUDA OOM, missing driver).
# CPU + int8 fits anywhere but transcribes ~10x slower.
MODEL_DEVICE_FALLBACK = "cpu"
MODEL_COMPUTE_TYPE_FALLBACK = "int8"


# =============================================================================
# Locale (Swiss German / CH-DE)
# =============================================================================

# Whisper accepts only ISO-639-1 codes (no "de-CH"); we use "de" and rely on
# the Swiss-flavored vocabulary in the prompt + the PIPELINE_RULES below to
# push output toward Swiss-German orthography (ß → ss).
DEFAULT_LANGUAGE = "de"

# Server-side default initial_prompt, used when a request omits `prompt`.
# Vocabulary cloud (no framing words like "Brief"/"Bericht"/"Notiz") so it
# biases medical-jargon spelling without pushing short CMS-field inputs
# toward letter-style salutations or sign-offs. Includes Swiss-specific
# terms (Spital, Krankenkasse, FMH, CHF) to bias toward CH-DE rather than
# DE-DE conventions.
DEFAULT_PROMPT: "str | None" = (
    "Medizin: Anamnese, Diagnose, Befund, Therapie, Medikation, Dosierung, "
    "ICD-10, mg, ml, Z.n., Hypertonie, Diabetes mellitus, Patient, Spital, "
    "Hausarzt, Praxis, Krankenkasse, Dr. med., FMH, CHF, Herr, Frau."
)


# =============================================================================
# Text post-processing pipeline (PIPELINE_RULES)
# =============================================================================
# A single ordered list of rules applied to the joined transcript. Each rule
# is one of:
#   - "regex"                       — pattern + replacement (re.sub)
#   - "callback:lowercase-wordlist" — strip terminator, lowercase next word if in wordlist
#   - "callback:map"                — auto-built alternation of map keys; lookup replacement
#   - "callback:dedup"              — collapse adjacent punctuation (last-non-comma wins)
#   - "callback:upper"              — capitalize after sentence terminator
#   - "terminal"                    — final lstrip(" \t\r") + rstrip(" \t\r"); always last
#
# Rules are reorderable, disable-able, and resettable from the admin WebUI
# (/config). The 13 seeded defaults below + 1 terminal trim row are the
# canonical pipeline for Swiss-German dictation. Custom rules (with
# `seeded: False`) can be added at any non-terminal position via the WebUI.
#
# Each rule's regex pattern is precompiled in main.rebuild_caches() at module
# load and again when the WebUI saves changes (CACHE_REBUILD_FIELDS).
PIPELINE_RULES: list[dict] = [
    {
        "name": "replace-szet-lc",
        "label": "Replace ß → ss",
        "type": "regex",
        "pattern": "ß",
        "replacement": "ss",
        "enabled": True, "locked": False, "seeded": True,
    },
    {
        "name": "replace-szet-uc",
        "label": "Replace ẞ → SS",
        "type": "regex",
        "pattern": "ẞ",
        "replacement": "SS",
        "enabled": True, "locked": False, "seeded": True,
    },
    {
        # Anything in string.punctuation NOT in `./-:,?!` is removed, plus
        # the German low quote „. The remaining `./-:,?!` are kept for the
        # later strip rules' digit-protected logic.
        "name": "strip-non-keep-punct",
        "label": "Strip non-keep punctuation",
        "type": "regex",
        "pattern": r"[\"#$%&'()*+;<=>@\[\\\]^_`{|}~„]",
        "replacement": "",
        "enabled": True, "locked": False, "seeded": True,
    },
    {
        "name": "normalize-digit-range",
        "label": "Normalize digit-range hyphen → slash",
        "type": "regex",
        "pattern": r"(\d)\s*-\s*(\d)",
        "replacement": r"\1/\2",
        "enabled": True, "locked": False, "seeded": True,
    },
    {
        # Pass A: paired strip — match terminator + capital-word, strip the
        # terminator and lowercase the next word IFF it's in `wordlist`.
        # German nouns are always capitalized; the wordlist is non-nouns
        # (interrogatives, conjunctions, articles, etc.) — case-insensitive.
        "name": "strip-and-lowercase-non-noun",
        "label": "Strip + lowercase next non-noun",
        "type": "callback:lowercase-wordlist",
        "pattern": r"(?<!\d)[.?!](\s*)([A-ZÄÖÜ])(\w*)",
        "wordlist": [
            # Interrogatives
            "wie", "was", "wer", "wann", "wo", "warum", "wieso", "weshalb",
            "welche", "welcher", "welches", "welchem", "welchen",
            # Conjunctions
            "und", "oder", "aber", "doch", "denn", "weil", "wenn", "dann",
            "dass", "obwohl", "während", "sondern", "deshalb", "trotzdem",
            "falls", "ob",
            # Articles
            "der", "die", "das", "den", "dem", "des",
            "ein", "eine", "einer", "einem", "einen", "eines",
            "kein", "keine", "keiner", "keinem", "keinen",
            # Common adverbs / particles
            "auch", "nur", "noch", "schon", "hier", "da", "dort",
            "heute", "morgen", "gestern", "jetzt", "nicht",
            "sehr", "ganz", "etwas", "viel", "wenig", "oft", "immer",
            # Common prepositions
            "in", "auf", "an", "von", "mit", "zu", "bei", "aus",
            "über", "unter", "vor", "nach", "für", "gegen", "ohne", "um",
            "durch", "ab", "seit",
            # Common verb forms at sentence start
            "ist", "sind", "war", "waren", "hat", "haben",
            "wird", "werden", "kann", "soll", "muss", "will",
            "könnte", "sollte", "müsste", "wollte",
        ],
        "enabled": True, "locked": False, "seeded": True,
    },
    {
        # Plain strip — catches lone .?! the paired pass missed PLUS soft-pause
        # commas (digit-protected: "1,000" survives; "Frau, Müller" loses the
        # comma). Replacement is empty; no side effects.
        "name": "strip-only-terminators-and-commas",
        "label": "Strip-only terminators + commas",
        "type": "regex",
        "pattern": r"(?<!\d)[.?!]|(?<!\d),|,(?!\d)",
        "replacement": "",
        "enabled": True, "locked": False, "seeded": True,
    },
    {
        # Spoken word → literal symbol. Word-bounded, case-insensitive.
        # Multi-word phrases (e.g. "eckige Klammer auf") MUST appear before
        # their single-word components — main.py sorts the keys longest-first
        # when building the alternation regex, so the longest phrase wins.
        #
        # Tradeoff: a dictation system can't distinguish noun-Punkt from
        # symbol-Punkt — substitutions are unconditional. Untick `enabled`
        # for "verbatim" mode.
        "name": "dictation-map",
        "label": "Dictation map",
        "type": "callback:map",
        "map": {
            # --- Multi-word phrases ----------------------------------------
            "neuer Absatz": "\n\n",
            "neuer Absätze": "\n\n",
            "neue Absätze": "\n\n",
            "neuer Apfel": "\n\n",
            "neue Zeile": "\n",
            "neue Zeilen": "\n",
            "neue Teile": "\n",
            "neue Seile": "\n",
            "neue Säule": "\n",
            "eckige Klammer auf": "[",
            "eckige Klammer zu": "]",
            "geschweifte Klammer auf": "{",
            "geschweifte Klammer zu": "}",
            "Anführungszeichen unten": "„",
            "Anführungszeichen oben": "“",
            "Klammer auf": "(",
            "Klammer zu": ")",
            "kleiner als": "<",
            "größer als": ">",
            # --- Single-word punctuation -----------------------------------
            "Punkt": ".",
            "Komma": ",",
            "Doppelpunkt": ":",
            "Semikolon": ";",
            "Strichpunkt": ";",
            "Fragezeichen": "?",
            "Ausrufezeichen": "!",
            "Ausrufungszeichen": "!",
            "Bindestrich": "-",
            "Trennstrich": "-",
            "Gedankenstrich": "–",
            "Schrägstrich": "/",
            "Backslash": "\\",
            "Apostroph": "'",
            "Unterstrich": "_",
            "Sternchen": "*",
            "Raute": "#",
            "Gänsefüßchen": '"',
            "Gänsefüsschen": '"',
            # "Franken" → "CHF" (not "Fr.") to avoid Step CAPITALIZE wrongly
            # uppercasing the next word ("Fr. Pro" → "Fr. pro").
            "Franken": "CHF",
            "Frankenzeichen": "CHF",
            # --- Math / typographic symbols --------------------------------
            "Prozent": "%",
            "Prozentzeichen": "%",
            "Paragraph": "§",
            "Paragraphenzeichen": "§",
            "Grad": "°",
            "Gradzeichen": "°",
            "Klammeraffe": "@",
            "Plus": "+",
            "Pluszeichen": "+",
            "Minus": "-",
            "Minuszeichen": "-",
            "Gleich": "=",
            "Gleichheitszeichen": "=",
            "Tilde": "~",
            "Pipe": "|",
            "Dach": "^",
            "Eurozeichen": "€",
            "Dollarzeichen": "$",
            "Et-Zeichen": "&",
            "Und-Zeichen": "&",
            "Kaufmannsund": "&",
        },
        "enabled": True, "locked": True, "seeded": True,
    },
    {
        "name": "space-before-closing-punct",
        "label": "Remove space before closing punctuation",
        "type": "regex",
        "pattern": r"[ \t]+([,.:;!?\)\]\}])",
        "replacement": r"\1",
        "enabled": True, "locked": True, "seeded": True,
    },
    {
        "name": "space-after-opening-punct",
        "label": "Remove space after opening punctuation",
        "type": "regex",
        "pattern": r"([\(\[\{])[ \t]+",
        "replacement": r"\1",
        "enabled": True, "locked": True, "seeded": True,
    },
    {
        # NEW vs the previous 11-step pipeline. Whisper segments are joined
        # with empty separator — if both adjacent segments end/start with
        # whitespace the join produces an interior double-space that no other
        # rule cleans (TIDY SPACING only matches whitespace adjacent to
        # punctuation).
        "name": "collapse-multi-space",
        "label": "Collapse multi-space",
        "type": "regex",
        "pattern": r"  +",
        "replacement": " ",
        "enabled": True, "locked": True, "seeded": True,
    },
    {
        # Whisper emits its own commas as soft pauses around dictation
        # keywords. After substitution we get runs like ",." (Punkt) or ",;"
        # (Semikolon). The user's intended mark wins: prefer any non-comma
        # in the run, and within non-commas prefer the LAST one (dictation
        # came after the Whisper pause). Pure commas collapse to one comma.
        "name": "dedup-punct",
        "label": "Dedup punctuation runs",
        "type": "callback:dedup",
        "pattern": r"[,.:;!?]{2,}",
        "enabled": True, "locked": True, "seeded": True,
    },
    {
        # Around a dictation-emitted "\n" / "\n\n" we often have residue: a
        # Whisper-emitted comma ("Müller, \n"), trailing space (" \n"), or
        # punctuation that leaked through ("\n , Welt"). Collapse the
        # neighborhood — optional whitespace + optional comma — on each side.
        "name": "tidy-newlines",
        "label": "Tidy newlines",
        "type": "regex",
        "pattern": r"[ \t]*,?[ \t]*(\n+)[ \t]*,?[ \t]*",
        "replacement": r"\1",
        "enabled": True, "locked": True, "seeded": True,
    },
    {
        # After dictation inserts ".", "?", "!", "\n", "\n\n", the following
        # letter starts a new sentence/paragraph. Whisper has no idea about
        # our substitution, so it leaves the next letter lowercase.
        "name": "capitalize-after-terminator",
        "label": "Capitalize after sentence terminator",
        "type": "callback:upper",
        "pattern": r"([.?!]\s+|\n+\s*)([a-zäöüß])",
        "enabled": True, "locked": True, "seeded": True,
    },
    {
        # Final, hardcoded — runs after the loop. lstrip+rstrip strip leading
        # and trailing space/tab/CR but NOT \n, so a user-dictated leading or
        # trailing "neue Zeile" ("\n") at the edges of the utterance survives.
        "name": "trim-edges",
        "label": "Trim edges (always-last)",
        "type": "terminal",
        "enabled": True, "locked": True, "seeded": True,
    },
]


# =============================================================================
# Logging
# =============================================================================

# Default log file path lives next to this file in logs/. Changing it doesn't
# require the directory to exist; main.py creates it at startup.
LOG_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "logs", "whisper.log")

# Rotation: 10 MB per file, keep 10 historical files (~100 MB max).
LOG_MAX_BYTES = 10 * 1024 * 1024
LOG_BACKUP_COUNT = 10

# Print a fancy multi-line trace block for every transcription request.
# Disable for production / high-traffic deployments where the log volume
# becomes problematic.
TRACE_ENABLED = True


# =============================================================================
# Server (uvicorn)
# =============================================================================

SERVER_HOST = "0.0.0.0"
SERVER_PORT = 8000
SERVER_WORKERS = 1          # faster-whisper holds models in memory; >1 multiplies VRAM
SERVER_LOG_LEVEL = "info"


# =============================================================================
# Whisper transcribe defaults (passed to WhisperModel.transcribe)
# =============================================================================

# Beam search width. Higher = better quality, slower. 10 is generous;
# turbo/distill models often work fine at 5.
BEAM_SIZE = 10
BEST_OF = 5

# Use the bundled Silero VAD to skip non-speech audio. Cuts wall time on
# files with long silences; rarely worth disabling.
VAD_FILTER = True

# Silero VAD parameters. The library defaults (min_silence_duration_ms=2000,
# speech_pad_ms=400) are tuned for long-form audio and EAT short dictation
# clips — a 2-3 s utterance with brief leading/trailing silence collapses to
# zero segments. The values below work for both short clips and long-form;
# tighten further (250 / 100) for very short clips.
VAD_MIN_SILENCE_MS: int = 500
VAD_SPEECH_PAD_MS: int = 200
VAD_THRESHOLD: float = 0.5

# Pass each segment's text into the prompt context for the next segment.
# Improves consistency on long-form audio; adds a tiny amount of latency.
# WARNING: many German finetunes (primeline-derived: tnfru, GalaktischeGurke,
# conkhidan) collapse to repeated punctuation when this is True. Set False if
# your selected model's card says so.
CONDITION_ON_PREVIOUS_TEXT = True

# Compute word-level timestamps via DTW alignment. Required for the
# `timestamp_granularities=["word"]` API option but EXPENSIVE and known to
# break certain finetunes (faster-whisper#1212): finetuned Whisper models
# can produce negative DTW timestamps which faster-whisper silently drops,
# leaving you with 0 segments. Set to False to disable word-level DTW for
# all requests — segment-level timestamps still work. Note: this takes
# precedence over the per-request `timestamp_granularities` field.
WORD_TIMESTAMPS_ENABLED = True

# Quality-check thresholds passed straight to model.transcribe(). Whisper
# drops a segment when:
#   no_speech_prob > NO_SPEECH_THRESHOLD  AND  avg_logprob < LOG_PROB_THRESHOLD
# OR when the segment text's gzip ratio exceeds COMPRESSION_RATIO_THRESHOLD.
# Finetunes can shift the no_speech distribution enough that these checks
# drop all real speech ("0 segments" symptom). When VAD_FILTER is True,
# faster-whisper Discussion #349 recommends setting all three to None so
# the VAD is the only gate. Use None to disable a check.
NO_SPEECH_THRESHOLD: "float | None" = 0.6
LOG_PROB_THRESHOLD: "float | None" = -1.0
COMPRESSION_RATIO_THRESHOLD: "float | None" = 2.4


# =============================================================================
# Whisper transcribe defaults — advanced (most users keep defaults)
# =============================================================================

# Persistent vocabulary biasing. Re-injected into the prompt of every decoder
# window — distinct from DEFAULT_PROMPT (which fades as decoded text
# accumulates). Useful for domain terms, drug names, person names. Ignored
# when prefix is set per-call.
DEFAULT_HOTWORDS: "str | None" = None

# Temperature fallback ladder (comma-separated floats). The decoder retries
# at each temperature when compression / log-prob checks fail. Ship the
# faster-whisper / OpenAI Whisper standard ladder explicitly so the admin UI's
# "Reset to default" gives users the safety net (a single value disables the
# fallback ladder and lets hallucination loops slip through). Empty = library
# default (currently identical, but explicit is safer for surprises).
TEMPERATURE: "str | None" = "0.0,0.2,0.4,0.6,0.8,1.0"

# Beam search patience; >1 keeps the beam alive longer. Default 1.0.
PATIENCE: float = 1.0

# Beam scoring length-norm exponent. >1 favors longer outputs. Default 1.0.
LENGTH_PENALTY: float = 1.0

# Multiplies logit of already-emitted tokens by 1/penalty. >1 discourages
# repetition loops. Default 1.0 (off). Try 1.05–1.2 for stutter audio.
REPETITION_PENALTY: float = 1.0

# Hard ban on n-grams of this size repeating. 0 = off.
NO_REPEAT_NGRAM_SIZE: int = 0

# Drop the running text prompt when temperature ladder fallback exceeds this
# value. Default 0.5. Only relevant when CONDITION_ON_PREVIOUS_TEXT=True.
PROMPT_RESET_ON_TEMPERATURE: float = 0.5


# =============================================================================
# Language detection (active when DEFAULT_LANGUAGE is empty)
# =============================================================================

# Re-detect language on every segment instead of only the first.
MULTILINGUAL: bool = False

# Min probability for the top language token to be accepted.
LANGUAGE_DETECTION_THRESHOLD: float = 0.5

# How many leading 30 s chunks to sample for language detection.
LANGUAGE_DETECTION_SEGMENTS: int = 1


# =============================================================================
# Anti-hallucination & token control
# =============================================================================

# With WORD_TIMESTAMPS_ENABLED, skip silent stretches longer than this many
# seconds when a possible hallucination is suspected. None = disabled.
HALLUCINATION_SILENCE_THRESHOLD: "float | None" = None

# Suppress blank token at start of decoder sampling. Default True. Almost
# never disable; only useful when debugging tokenizer behavior.
SUPPRESS_BLANK: bool = True

# Comma-separated token IDs to ban from output. "-1" = expand to model's
# default non-speech set; "" = no suppression.
SUPPRESS_TOKENS: "str | None" = "-1"

# Single chars to hard-mask via the loaded model's tokenizer. Resolved at
# request time to vocab IDs and merged into the effective suppress_tokens
# list. Empty / None = no extra suppression. Set to ".,?!:;" for verbatim
# dictation: model can't auto-insert punctuation, so spoken "Punkt" /
# "Komma" surface as words for the dictation-map PIPELINE_RULE to convert.
SUPPRESS_CHARS: "str | None" = None

# With WORD_TIMESTAMPS_ENABLED, glue these characters onto the FOLLOWING /
# PRECEDING word's timing. Locale-specific.
PREPEND_PUNCTUATIONS: str = "\"'“¿([{-"
APPEND_PUNCTUATIONS: str = "\"'.。,，!！?？:：”)]}、"


# =============================================================================
# Output wrappers — backend-level, NOT a faster-whisper param
# =============================================================================
# Plain strings prepended/appended to the final transcript text after the
# post-processing pipeline runs (before the final whitespace trim). Use to
# tag transcripts with model-specific banners, e.g.:
#   OUTPUT_PREFIX = "[de] "
#   OUTPUT_SUFFIX = " (errors possible)"
# Per-model overrides via MODEL_OVERRIDES win.
OUTPUT_PREFIX: str = ""
OUTPUT_SUFFIX: str = ""


# =============================================================================
# Load-time, hardware (advanced)
# =============================================================================

# Directory where HuggingFace model snapshots are cached. None = standard
# HF cache dir (~/.cache/huggingface).
DOWNLOAD_ROOT: "str | None" = None

# If True, never hit the network — only resolve from local cache.
LOCAL_FILES_ONLY: bool = False

# HuggingFace auth token for gated/private repos. None = no token.
USE_AUTH_TOKEN: "str | None" = None

# Auto-convert HuggingFace transformers Whisper models to CTranslate2 format
# on first load (when no model.bin is present). Requires
# `pip install -r requirements-convert.txt`.
AUTO_CONVERT_HF_MODELS: bool = False

# On-disk weight quantisation for auto-conversion. Independent of
# MODEL_COMPUTE_TYPE; CT2 up/down-casts at load.
CONVERT_QUANTIZATION: str = "float16"

# Output root for auto-converted CT2 models. None = ~/.cache/whisper-ct2.
CONVERTED_MODELS_DIR: "str | None" = None

# CPU threads for inference. 0 = library default (typically 4).
CPU_THREADS: int = 0

# Replicates the model so concurrent transcribe() calls run in true parallel.
# Costs ~Nx VRAM for activation buffers (weights are shared).
NUM_WORKERS: int = 1

# GPU index to bind to. 0 = first CUDA device.
DEVICE_INDEX: int = 0


# =============================================================================
# Per-model overrides (MODEL_OVERRIDES)
# =============================================================================
# Map of model_id -> dict of override fields. Each override may set any
# per-model-overrideable field; absent fields inherit the global default.
# Edited via the per-model pane of the admin UI; persisted in
# config.local.json. Env-var convention to pin per-model fields:
#   WHISPER_MODEL_OVERRIDE__<encoded_id>__<FIELD>
# where <encoded_id> URL-encodes "/" as "__SLASH__" and "." as "__DOT__".
MODEL_OVERRIDES: "dict[str, dict[str, object]]" = {}


# =============================================================================
# Admin WebUI (optional /config browser editor)
# =============================================================================
# Both off by default. The /config endpoints are only registered when
# ADMIN_UI_ENABLED is True. If ADMIN_TOKEN is None, the loopback-only check
# is the sole gate — fine on a single-user machine, but set a token if you
# want a second factor against other local users / processes.
#
# Generate a strong token with PowerShell:
#   [Convert]::ToBase64String([Security.Cryptography.RandomNumberGenerator]::GetBytes(32))
#
# These are intentionally NOT editable from the admin WebUI itself (avoids
# foot-gun where you lock yourself out by toggling them in the browser).
ADMIN_UI_ENABLED = True
ADMIN_TOKEN: "str | None" = None
# Bearer token for end-user access to /quick-config (the simplified page
# exposing only rules the admin has flagged with `exposed: true`). Distinct
# from ADMIN_TOKEN; ADMIN_TOKEN also satisfies /quick-config auth.
USER_TOKEN: "str | None" = None

# Allowlist of IPs / CIDRs allowed to reach the /config admin endpoints.
# Loopback (127.0.0.1, ::1) is ALWAYS implicitly allowed — even if you put
# a typo here you can still reach the page from the box itself.
# Examples:
#   ["127.0.0.1", "::1"]                       # default — loopback only
#   ["127.0.0.1", "::1", "192.168.1.0/24"]     # also a LAN subnet
#   ["0.0.0.0/0"]                              # anywhere (NOT recommended)
ADMIN_ALLOWED_HOSTS: "list[str]" = ["127.0.0.1", "::1"]

# Same for /stats. Default loopback-only.
STATS_ALLOWED_HOSTS: "list[str]" = ["127.0.0.1", "::1"]


# =============================================================================
# Transcription error reports
# =============================================================================
# Users can flag a wrong transcription from /quick-config; admins triage on
# /reports. The store is durable PHI: plaintext SQLite next to
# config.local.json. Whole-disk encryption is the deployment's responsibility.

# DB file path. Default sits next to config.local.json. SQLite uses three
# files at runtime (.sqlite3, -wal, -shm); .gitignore matches all three.
REPORTS_DB = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "reports.local.sqlite3"
)

# Soft cap. On overflow create_report() evicts oldest closed reports first
# (resolved/dismissed), then oldest open. Tune lower for memory-tight LAN
# deployments; the admin page is client-side filtered so the practical
# upper bound is around what a browser can render in one DOM.
REPORTS_MAX = 1000

# Auto-delete reports older than this many days. Sweep runs on startup and
# hourly thereafter. Set to 0 to disable (admin must clear manually).
REPORTS_RETENTION_DAYS = 90

# Master switch for end-user (USER_TOKEN role) report submission. Set to
# False to make /quick-config/reports/api/submit return 403 for everyone
# except admins. The button stays visible but submission is rejected.
REPORTS_ALLOW_USER_SUBMIT = True


# =============================================================================
# Whisper fine-tuning capture store
# =============================================================================
# Optional pipeline that persists the original audio + word-level timestamps
# next to the model's raw/final transcription so an admin can review each
# clip karaoke-style on /captures and produce ground-truth text for Whisper
# fine-tuning. Default OFF — audio is biometric-grade PHI; the master
# switch demands an explicit opt-in.
#
# Storage layout:
#   CAPTURES_DB  — SQLite (WAL), metadata + word timestamps + corrections
#   CAPTURES_DIR — filesystem root for audio (4-char fanout subdirs)
#
# Export endpoint streams a tar.gz containing manifest.jsonl + audio/<id>.<ext>,
# loadable via huggingface `datasets.load_dataset('json', data_files=...)`.

# Master switch — when False, the transcribe handler never copies audio
# and never inserts a capture row. Browsing /captures still works
# (existing rows visible).
CAPTURE_RECORDINGS_ENABLED = False

CAPTURES_DB = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "captures.local.sqlite3"
)
CAPTURES_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "captures"
)

# Soft caps. On overflow, _evict_to_cap drops rows in priority order:
# dismissed → audio_missing → reviewed → new → ready. Training-quality
# ("ready") wins; unreviewed work ("new") is also protected.
CAPTURES_MAX = 5000
CAPTURES_MAX_MB = 5000

# Auto-delete captures older than this many days. Sweep runs on startup
# and hourly thereafter. 0 = disabled.
CAPTURES_RETENTION_DAYS = 365

# Sampling: 1.0 captures every eligible request, 0.1 captures ~10% etc.
# Decision is made per-request before transcribe runs.
CAPTURE_RECORDINGS_SAMPLE_RATE = 1.0

# Duration filter — too-short clips are usually false starts, too-long
# ones strain memory and need re-segmentation before fine-tuning anyway.
CAPTURE_RECORDINGS_MIN_DURATION_SEC = 0.5
CAPTURE_RECORDINGS_MAX_DURATION_SEC = 600.0

# Pre-transcribe size guard: skip eligibility roll for uploads larger
# than this many bytes. Keeps a misbehaving client from filling the
# captures dir with multi-100MB blobs.
CAPTURE_RECORDINGS_AUDIO_BYTES_HARD_LIMIT = 100_000_000


# Snapshot the in-file defaults BEFORE config.local.json + env overrides apply.
# Used by main.py's request log block to mark non-default scalar values with
# `*` so the operator can see at a glance which knobs are overridden.
_BASELINE: "dict[str, object]" = {
    k: v for k, v in globals().items()
    if k.isupper() and not k.startswith("_")
}


# =============================================================================
# Runtime overrides from config.local.json (admin WebUI)
# =============================================================================
# Loaded between in-file defaults and env-var overrides so precedence is:
#     ENV var  >  config.local.json  >  in-file default (above)
# Failure to load NEVER raises — see config_store.load_overrides for details.
try:
    from config_store import load_overrides as _load_overrides

    for _k, _v in _load_overrides().items():
        globals()[_k] = _v
except ImportError:
    # config_store depends on pydantic; if it isn't installed we still want
    # config.py to import cleanly so the rest of the app can run.
    pass


# =============================================================================
# Environment variable overrides (deployment-time)
# =============================================================================
# Anything below here lets the env var win over the in-file default. Touch
# only if you want to change the override syntax itself.

DEFAULT_MODEL = os.environ.get("WHISPER_DEFAULT_MODEL", DEFAULT_MODEL)

_env_allowed = os.environ.get("WHISPER_ALLOWED_MODELS")
if _env_allowed is not None:
    ALLOWED_MODELS = {s.strip() for s in _env_allowed.split(",") if s.strip()}

MAX_LOADED_MODELS = int(os.environ.get("WHISPER_MAX_LOADED_MODELS", str(MAX_LOADED_MODELS)))
MODEL_IDLE_TIMEOUT_S = int(os.environ.get("WHISPER_MODEL_IDLE_TIMEOUT_S", str(MODEL_IDLE_TIMEOUT_S)))

_env_preload = os.environ.get("WHISPER_PRELOAD_MODELS")
if _env_preload is not None:
    PRELOAD_MODELS = [s.strip() for s in _env_preload.split(",") if s.strip()]

_env_prompt = os.environ.get("WHISPER_DEFAULT_PROMPT")
if _env_prompt is not None:
    DEFAULT_PROMPT = _env_prompt or None  # explicit empty string => disable

TRACE_ENABLED = os.environ.get("WHISPER_TRACE", "1" if TRACE_ENABLED else "0") == "1"

LOG_FILE = os.environ.get("WHISPER_LOG_FILE", LOG_FILE)

# WHISPER_ADMIN_UI: "1" to enable, anything else (or unset) to disable.
ADMIN_UI_ENABLED = os.environ.get("WHISPER_ADMIN_UI", "1" if ADMIN_UI_ENABLED else "0") == "1"

# WHISPER_ADMIN_TOKEN: empty string is treated the same as "no token".
_env_admin_token = os.environ.get("WHISPER_ADMIN_TOKEN")
if _env_admin_token is not None:
    ADMIN_TOKEN = _env_admin_token or None

# WHISPER_USER_TOKEN: empty string is treated the same as "no token".
_env_user_token = os.environ.get("WHISPER_USER_TOKEN")
if _env_user_token is not None:
    USER_TOKEN = _env_user_token or None

# Comma-separated CIDR/IP allowlists for /config and /stats. Empty string is
# treated as "no override" (use the in-file / local.json value).
_env_admin_hosts = os.environ.get("WHISPER_ADMIN_ALLOWED_HOSTS")
if _env_admin_hosts is not None and _env_admin_hosts.strip():
    ADMIN_ALLOWED_HOSTS = [s.strip() for s in _env_admin_hosts.split(",") if s.strip()]

_env_stats_hosts = os.environ.get("WHISPER_STATS_ALLOWED_HOSTS")
if _env_stats_hosts is not None and _env_stats_hosts.strip():
    STATS_ALLOWED_HOSTS = [s.strip() for s in _env_stats_hosts.split(",") if s.strip()]


# --- Reports store --------------------------------------------------------
_env_reports_db = os.environ.get("WHISPER_REPORTS_DB")
if _env_reports_db is not None and _env_reports_db.strip():
    REPORTS_DB = _env_reports_db.strip()

_env_reports_max = os.environ.get("WHISPER_REPORTS_MAX")
if _env_reports_max is not None and _env_reports_max.strip():
    try:
        REPORTS_MAX = int(_env_reports_max)
    except ValueError:
        pass

_env_reports_retention = os.environ.get("WHISPER_REPORTS_RETENTION_DAYS")
if _env_reports_retention is not None and _env_reports_retention.strip():
    try:
        REPORTS_RETENTION_DAYS = int(_env_reports_retention)
    except ValueError:
        pass

_env_reports_allow_user = os.environ.get("WHISPER_REPORTS_ALLOW_USER_SUBMIT")
if _env_reports_allow_user is not None and _env_reports_allow_user.strip():
    REPORTS_ALLOW_USER_SUBMIT = _env_reports_allow_user.strip().lower() in (
        "1", "true", "yes", "on"
    )


# --- Captures (fine-tuning data store) ------------------------------------

def _truthy(s: str) -> bool:
    return s.strip().lower() in ("1", "true", "yes", "on")

_env_cap_enabled = os.environ.get("WHISPER_CAPTURE_RECORDINGS_ENABLED")
if _env_cap_enabled is not None and _env_cap_enabled.strip():
    CAPTURE_RECORDINGS_ENABLED = _truthy(_env_cap_enabled)

_env_cap_db = os.environ.get("WHISPER_CAPTURES_DB")
if _env_cap_db is not None and _env_cap_db.strip():
    CAPTURES_DB = _env_cap_db.strip()

_env_cap_dir = os.environ.get("WHISPER_CAPTURES_DIR")
if _env_cap_dir is not None and _env_cap_dir.strip():
    CAPTURES_DIR = _env_cap_dir.strip()

_env_cap_max = os.environ.get("WHISPER_CAPTURES_MAX")
if _env_cap_max is not None and _env_cap_max.strip():
    try:
        CAPTURES_MAX = int(_env_cap_max)
    except ValueError:
        pass

_env_cap_max_mb = os.environ.get("WHISPER_CAPTURES_MAX_MB")
if _env_cap_max_mb is not None and _env_cap_max_mb.strip():
    try:
        CAPTURES_MAX_MB = int(_env_cap_max_mb)
    except ValueError:
        pass

_env_cap_retention = os.environ.get("WHISPER_CAPTURES_RETENTION_DAYS")
if _env_cap_retention is not None and _env_cap_retention.strip():
    try:
        CAPTURES_RETENTION_DAYS = int(_env_cap_retention)
    except ValueError:
        pass

_env_cap_sample = os.environ.get("WHISPER_CAPTURE_RECORDINGS_SAMPLE_RATE")
if _env_cap_sample is not None and _env_cap_sample.strip():
    try:
        CAPTURE_RECORDINGS_SAMPLE_RATE = float(_env_cap_sample)
    except ValueError:
        pass

_env_cap_min = os.environ.get("WHISPER_CAPTURE_RECORDINGS_MIN_DURATION_SEC")
if _env_cap_min is not None and _env_cap_min.strip():
    try:
        CAPTURE_RECORDINGS_MIN_DURATION_SEC = float(_env_cap_min)
    except ValueError:
        pass

_env_cap_maxdur = os.environ.get("WHISPER_CAPTURE_RECORDINGS_MAX_DURATION_SEC")
if _env_cap_maxdur is not None and _env_cap_maxdur.strip():
    try:
        CAPTURE_RECORDINGS_MAX_DURATION_SEC = float(_env_cap_maxdur)
    except ValueError:
        pass

_env_cap_hardlim = os.environ.get("WHISPER_CAPTURE_RECORDINGS_AUDIO_BYTES_HARD_LIMIT")
if _env_cap_hardlim is not None and _env_cap_hardlim.strip():
    try:
        CAPTURE_RECORDINGS_AUDIO_BYTES_HARD_LIMIT = int(_env_cap_hardlim)
    except ValueError:
        pass


# --- Advanced decode params -------------------------------------------------

_env_hotwords = os.environ.get("WHISPER_DEFAULT_HOTWORDS")
if _env_hotwords is not None:
    DEFAULT_HOTWORDS = _env_hotwords or None

_env_temperature = os.environ.get("WHISPER_TEMPERATURE")
if _env_temperature is not None:
    TEMPERATURE = _env_temperature or None

_env_patience = os.environ.get("WHISPER_PATIENCE")
if _env_patience is not None:
    try:
        PATIENCE = float(_env_patience)
    except ValueError:
        pass

_env_length_penalty = os.environ.get("WHISPER_LENGTH_PENALTY")
if _env_length_penalty is not None:
    try:
        LENGTH_PENALTY = float(_env_length_penalty)
    except ValueError:
        pass

_env_repetition_penalty = os.environ.get("WHISPER_REPETITION_PENALTY")
if _env_repetition_penalty is not None:
    try:
        REPETITION_PENALTY = float(_env_repetition_penalty)
    except ValueError:
        pass

_env_no_repeat_ngram = os.environ.get("WHISPER_NO_REPEAT_NGRAM_SIZE")
if _env_no_repeat_ngram is not None:
    try:
        NO_REPEAT_NGRAM_SIZE = int(_env_no_repeat_ngram)
    except ValueError:
        pass

_env_prompt_reset_t = os.environ.get("WHISPER_PROMPT_RESET_ON_TEMPERATURE")
if _env_prompt_reset_t is not None:
    try:
        PROMPT_RESET_ON_TEMPERATURE = float(_env_prompt_reset_t)
    except ValueError:
        pass


# --- Language detection -----------------------------------------------------

_env_multilingual = os.environ.get("WHISPER_MULTILINGUAL")
if _env_multilingual is not None:
    MULTILINGUAL = _env_multilingual == "1"

_env_lang_thresh = os.environ.get("WHISPER_LANGUAGE_DETECTION_THRESHOLD")
if _env_lang_thresh is not None:
    try:
        LANGUAGE_DETECTION_THRESHOLD = float(_env_lang_thresh)
    except ValueError:
        pass

_env_lang_segments = os.environ.get("WHISPER_LANGUAGE_DETECTION_SEGMENTS")
if _env_lang_segments is not None:
    try:
        LANGUAGE_DETECTION_SEGMENTS = int(_env_lang_segments)
    except ValueError:
        pass


# --- Anti-hallucination & token control -------------------------------------

_env_hallu_silence = os.environ.get("WHISPER_HALLUCINATION_SILENCE_THRESHOLD")
if _env_hallu_silence is not None and _env_hallu_silence.strip():
    try:
        HALLUCINATION_SILENCE_THRESHOLD = float(_env_hallu_silence)
    except ValueError:
        pass

_env_supp_blank = os.environ.get("WHISPER_SUPPRESS_BLANK")
if _env_supp_blank is not None:
    SUPPRESS_BLANK = _env_supp_blank == "1"

_env_supp_tokens = os.environ.get("WHISPER_SUPPRESS_TOKENS")
if _env_supp_tokens is not None:
    SUPPRESS_TOKENS = _env_supp_tokens or None

_env_supp_chars = os.environ.get("WHISPER_SUPPRESS_CHARS")
if _env_supp_chars is not None:
    SUPPRESS_CHARS = _env_supp_chars or None

_env_prepend_punct = os.environ.get("WHISPER_PREPEND_PUNCTUATIONS")
if _env_prepend_punct is not None:
    PREPEND_PUNCTUATIONS = _env_prepend_punct

_env_append_punct = os.environ.get("WHISPER_APPEND_PUNCTUATIONS")
if _env_append_punct is not None:
    APPEND_PUNCTUATIONS = _env_append_punct


# --- Output wrappers --------------------------------------------------------

_env_out_prefix = os.environ.get("WHISPER_OUTPUT_PREFIX")
if _env_out_prefix is not None:
    OUTPUT_PREFIX = _env_out_prefix

_env_out_suffix = os.environ.get("WHISPER_OUTPUT_SUFFIX")
if _env_out_suffix is not None:
    OUTPUT_SUFFIX = _env_out_suffix


# --- Load-time, hardware ----------------------------------------------------

_env_download_root = os.environ.get("WHISPER_DOWNLOAD_ROOT")
if _env_download_root is not None:
    DOWNLOAD_ROOT = _env_download_root or None

_env_local_files_only = os.environ.get("WHISPER_LOCAL_FILES_ONLY")
if _env_local_files_only is not None:
    LOCAL_FILES_ONLY = _env_local_files_only == "1"

_env_use_auth_token = os.environ.get("WHISPER_USE_AUTH_TOKEN")
if _env_use_auth_token is not None:
    USE_AUTH_TOKEN = _env_use_auth_token or None

_env_auto_convert = os.environ.get("WHISPER_AUTO_CONVERT_HF_MODELS")
if _env_auto_convert is not None:
    AUTO_CONVERT_HF_MODELS = _env_auto_convert == "1"

_env_convert_quant = os.environ.get("WHISPER_CONVERT_QUANTIZATION")
if _env_convert_quant is not None:
    CONVERT_QUANTIZATION = _env_convert_quant or "float16"

_env_converted_dir = os.environ.get("WHISPER_CONVERTED_MODELS_DIR")
if _env_converted_dir is not None:
    CONVERTED_MODELS_DIR = _env_converted_dir or None

_env_cpu_threads = os.environ.get("WHISPER_CPU_THREADS")
if _env_cpu_threads is not None:
    try:
        CPU_THREADS = int(_env_cpu_threads)
    except ValueError:
        pass

_env_num_workers = os.environ.get("WHISPER_NUM_WORKERS")
if _env_num_workers is not None:
    try:
        NUM_WORKERS = int(_env_num_workers)
    except ValueError:
        pass

_env_device_index = os.environ.get("WHISPER_DEVICE_INDEX")
if _env_device_index is not None:
    try:
        DEVICE_INDEX = int(_env_device_index)
    except ValueError:
        pass


# --- Per-model overrides via env (WHISPER_MODEL_OVERRIDE__<id>__<FIELD>) ----
# Convention: model id is encoded by replacing "/" with "__SLASH__" and "." with
# "__DOT__" so HF-style ids round-trip cleanly through env var names. Field
# names are UPPER_CASE matching the AdminConfig field. Values are parsed in
# the same way as their global counterparts (int, float, bool, string).
def _decode_model_id(s: str) -> str:
    return s.replace("__SLASH__", "/").replace("__DOT__", ".")


def _coerce_override_value(field: str, raw: str) -> object:
    """Coerce a raw env-var string to the right type for a ModelOverride field.
    Falls back to the raw string for fields we can't easily classify (the
    pydantic validator will catch type mismatches at save-merge time)."""
    bool_fields = {
        "CONDITION_ON_PREVIOUS_TEXT", "WORD_TIMESTAMPS_ENABLED",
        "VAD_FILTER", "MULTILINGUAL", "SUPPRESS_BLANK", "LOCAL_FILES_ONLY",
    }
    int_fields = {
        "BEAM_SIZE", "BEST_OF", "VAD_MIN_SILENCE_MS", "VAD_SPEECH_PAD_MS",
        "NO_REPEAT_NGRAM_SIZE", "LANGUAGE_DETECTION_SEGMENTS",
        "NUM_WORKERS", "DEVICE_INDEX", "CPU_THREADS",
    }
    float_fields = {
        "VAD_THRESHOLD", "NO_SPEECH_THRESHOLD", "LOG_PROB_THRESHOLD",
        "COMPRESSION_RATIO_THRESHOLD", "PATIENCE", "LENGTH_PENALTY",
        "REPETITION_PENALTY", "PROMPT_RESET_ON_TEMPERATURE",
        "LANGUAGE_DETECTION_THRESHOLD", "HALLUCINATION_SILENCE_THRESHOLD",
    }
    list_fields = {"PIPELINE_RULES_EXCLUDE"}
    if field in bool_fields:
        return raw == "1"
    if field in int_fields:
        try:
            return int(raw)
        except ValueError:
            return raw
    if field in float_fields:
        try:
            return float(raw)
        except ValueError:
            return raw
    if field in list_fields:
        return [s.strip() for s in raw.split(",") if s.strip()]
    return raw


_OVERRIDE_PREFIX = "WHISPER_MODEL_OVERRIDE__"
for _k, _v in os.environ.items():
    if not _k.startswith(_OVERRIDE_PREFIX):
        continue
    _rest = _k[len(_OVERRIDE_PREFIX):]
    # Split on the LAST "__<UPPER>" occurrence. We can't just split on "__"
    # because the encoded id contains "__SLASH__" and "__DOT__".
    # Strategy: find the last "__" that isn't part of __SLASH__/__DOT__ by
    # walking from the right.
    _idx = -1
    _i = len(_rest) - 1
    while _i >= 0:
        # find a "__" boundary
        _pos = _rest.rfind("__", 0, _i + 1)
        if _pos < 0:
            break
        # is it the boundary BEFORE __SLASH__ / __DOT__ / __FIELD__?
        # We're scanning right-to-left looking for the boundary that
        # separates the encoded id from the field name. Skip if the segment
        # to the right starts with one of our encoded markers.
        _tail = _rest[_pos + 2:]
        if _tail.startswith("SLASH__") or _tail.startswith("DOT__"):
            _i = _pos - 1
            continue
        _idx = _pos
        break
    if _idx <= 0:
        continue
    _enc_id = _rest[:_idx]
    _field = _rest[_idx + 2:]
    _model_id = _decode_model_id(_enc_id)
    _entry = MODEL_OVERRIDES.setdefault(_model_id, {})
    _entry[_field] = _coerce_override_value(_field, _v)
