"""
Configuration for faster-whisper-backend.

Edit the values in this file to tune the deployment. Each setting can ALSO
be overridden at runtime via a matching WHISPER_* environment variable (set
on the Windows Service via <env> elements in WhisperAPI.xml, generated by
install-service.ps1). The env var wins over the value here, so this file
holds the in-repo defaults and env vars hold per-machine overrides.

Conventions:
- Module attribute names are UPPER_CASE.
- Public symbols (no leading underscore) are intended to be edited.
- Algorithm code (regex compilation, pipeline functions) lives in main.py.
"""
import json
import os

# Load a local .env file (if present) before any os.environ reads below, so a
# `cp .env.example .env` works for bare `python main.py` as well as Docker.
# load_dotenv does NOT override variables already set in the real environment,
# so an exported env var / docker-compose `environment:` still wins over .env.
# Guarded: the app must still import if python-dotenv isn't installed.
try:
    from dotenv import load_dotenv as _load_dotenv

    _load_dotenv()
except ImportError:
    pass


# Directory holding this config file — used to anchor default paths for the
# log file and the per-feature SQLite stores. Hoisted because the literal
# `os.path.dirname(os.path.abspath(__file__))` recurred at 5 sites below.
# Underscore-prefixed so it's excluded from _BASELINE / the admin UI.
_REPO_DIR = os.path.dirname(os.path.abspath(__file__))


# =============================================================================
# Models
# =============================================================================

# Model loaded when a client sends `model="whisper-1"` (OpenAI default) or
# omits the field. Any faster-whisper short name or full HF repo id works.
# Examples:
#   "large-v2", "large-v3", "large-v3-turbo", "distil-large-v3"
#   "Systran/faster-whisper-large-v3"
#   "GalaktischeGurke/primeline-whisper-large-v3-german-ct2"
DEFAULT_MODEL = "large-v2"

# Restrict which models clients are allowed to load. An empty set means "any
# model name passes through" — convenient on a private LAN, but lets a client
# trigger a multi-GB download by sending an unknown name. Add entries to
# enforce a known list. Curated CH-DE / German starter set; uncomment to
# enable.
ALLOWED_MODELS: "set[str]" = {
    "large-v2",
    "large-v3",
    "GalaktischeGurke/primeline-whisper-large-v3-german-ct2",
    # --- Systran's official faster-whisper builds (auto-resolved from HF) ---
    # "large-v2",
    # "large-v3",
    # "large-v3-turbo",         # ~4x faster than large-v3, slight quality dip
    # "distil-large-v3",        # smaller; English-leaning, may regress on CH-DE

    # --- German-finetuned, pre-converted to CTranslate2 ----------------------
    # "GalaktischeGurke/primeline-whisper-large-v3-german-ct2",
    # "conkhidan/primeline-whisper-large-v3-turbo-german-ct2",
}

# Number of models to keep hot in VRAM. LRU eviction beyond this. Each
# large-v3 model is ~1.5 GB on float16 CUDA; turbo/distill variants are
# ~600 MB. Pick based on free VRAM after the OS / other apps.
MAX_LOADED_MODELS = 3

# Time-based eviction: unload a model after this many seconds without
# being used (touched on every transcribe). 0 disables time-based
# eviction (current behavior — only LRU-evict when MAX_LOADED_MODELS
# is exceeded). Common values: 1800 (30 min), 3600 (1 h), 14400 (4 h).
MODEL_IDLE_TIMEOUT_S = 0

# Models to load eagerly at server startup. Listed models stay hot in VRAM
# from boot, so the first request to each doesn't pay the 5-30 s warm-up.
# If empty, only DEFAULT_MODEL is preloaded (current/historical behavior).
# Keep len(PRELOAD_MODELS) <= MAX_LOADED_MODELS or LRU eviction starts
# fighting your own preloads. Order doesn't matter for behavior, only for
# load order at startup.
PRELOAD_MODELS: "list[str]" = [
    "large-v2",
    "large-v3",
    "GalaktischeGurke/primeline-whisper-large-v3-german-ct2",
]

# Primary load device + precision. CUDA + float16 is the GPU path.
MODEL_DEVICE = "cuda"
MODEL_COMPUTE_TYPE = "float16"

# Fallback if the primary load fails (e.g. CUDA OOM, missing driver).
# CPU + int8 fits anywhere but transcribes ~10x slower.
MODEL_DEVICE_FALLBACK = "cpu"
MODEL_COMPUTE_TYPE_FALLBACK = "int8"


# =============================================================================
# Locale (Swiss German / CH-DE)
# =============================================================================

# Whisper accepts only ISO-639-1 codes (no "de-CH"); we use "de" and rely on
# the Swiss-flavored vocabulary in the prompt + the PIPELINE_RULES below to
# push output toward Swiss-German orthography (ß → ss).
DEFAULT_LANGUAGE = "de"

# Server-side default initial_prompt, used when a request omits `prompt`.
# Vocabulary cloud (no framing words like "Brief"/"Bericht"/"Notiz") so it
# biases medical-jargon spelling without pushing short CMS-field inputs
# toward letter-style salutations or sign-offs. Includes Swiss-specific
# terms (Spital, Krankenkasse, FMH, CHF) to bias toward CH-DE rather than
# DE-DE conventions.
DEFAULT_PROMPT: "str | None" = (
    "Medizin: Anamnese, Diagnose, Befund, Therapie, Medikation, Dosierung, "
    "ICD-10, mg, ml, Z.n., Hypertonie, Diabetes mellitus, Patient, Spital, "
    "Hausarzt, Praxis, Krankenkasse, Dr. med., FMH, CHF, Herr, Frau."
)


# =============================================================================
# Text post-processing pipeline (PIPELINE_RULES)
# =============================================================================
# The ordered rule list applied to the joined transcript lives in the
# committed file config.json -- NOT in this module. The admin WebUI's
# "Defaults" mode edits config.json so rule fixes can be git-pushed to every
# deployment; config.local.json still layers per-deployment overrides on top
# (precedence: ENV > config.local.json > config.json).
#
# Each rule's `type` is one of:
#   - "regex"                       -- pattern + replacement (re.sub)
#   - "callback:lowercase-wordlist" -- strip terminator, lowercase next word if in wordlist
#   - "callback:map"                -- auto-built alternation of map keys; lookup replacement
#   - "callback:dedup"              -- collapse adjacent punctuation (last-non-comma wins)
#   - "callback:upper"              -- capitalize after sentence terminator
#   - "terminal"                    -- final lstrip(" \t\r") + rstrip(" \t\r"); always last
#
# Ordering invariants: dictation-map multi-word phrases must precede their
# single-word components (longest-first wins); the terminal rule is always
# last. See README ("Pipeline rules") for the full rationale.
#
# Each rule's regex pattern is precompiled in main.rebuild_caches() at module
# load and again when the WebUI saves changes (CACHE_REBUILD_FIELDS).
def _load_factory_pipeline_rules() -> "list[dict]":
    """Load the committed factory pipeline rules from config.json.

    Stdlib-only (no pydantic) so config.py imports even in a minimal
    environment; the admin save path validates with pydantic separately.
    Raises RuntimeError on a missing/corrupt file -- config.json is required
    and committed, so its absence is a deployment error, not a soft fallback.
    """
    import json
    _path = os.path.join(_REPO_DIR, "config.json")
    if not os.path.exists(_path):
        raise RuntimeError(
            f"config.json not found at {_path} -- it is required and committed "
            f"to the repository. Restore it with 'git checkout config.json'."
        )
    try:
        with open(_path, "r", encoding="utf-8") as _f:
            _raw = json.load(_f)
    except (OSError, json.JSONDecodeError) as _e:
        raise RuntimeError(f"config.json is unreadable or malformed: {_e}") from _e
    if not isinstance(_raw, dict) or not isinstance(_raw.get("PIPELINE_RULES"), list):
        raise RuntimeError(
            "config.json must be a JSON object with a 'PIPELINE_RULES' array"
        )
    return _raw["PIPELINE_RULES"]


PIPELINE_RULES: list[dict] = _load_factory_pipeline_rules()


# =============================================================================
# Logging
# =============================================================================

# Default log file path lives next to this file in logs/. Changing it doesn't
# require the directory to exist; main.py creates it at startup.
LOG_FILE = os.path.join(_REPO_DIR, "logs", "whisper.log")

# Rotation: 10 MB per file, keep 10 historical files (~100 MB max).
LOG_MAX_BYTES = 10 * 1024 * 1024
LOG_BACKUP_COUNT = 10

# /logs viewer tunables.
#
# LOG_VIEWER_INITIAL_LINES — backlog streamed to the /logs page on
# connect. When the active whisper.log has fewer lines than this (e.g.
# right after rotation), the reader spills into the rotated chain
# (whisper.log.1, .2, …) until the target is reached. Upper bound
# 100_000 caps disk + RAM cost.
LOG_VIEWER_INITIAL_LINES = 2000
#
# LOG_VIEWER_DOM_MAX — max number of log lines retained in the browser
# DOM during a live tail. 0 = auto (= LOG_VIEWER_INITIAL_LINES × 4),
# computed at template-render time. The cap applies only to the live-
# append path; "Load older" pagination grows the DOM beyond it.
LOG_VIEWER_DOM_MAX = 0

# Print a fancy multi-line trace block for every transcription request.
# Disable for production / high-traffic deployments where the log volume
# becomes problematic.
TRACE_ENABLED = True


# =============================================================================
# Server (uvicorn)
# =============================================================================

SERVER_HOST = "0.0.0.0"
SERVER_PORT = 8000
SERVER_WORKERS = 1          # faster-whisper holds models in memory; >1 multiplies VRAM
SERVER_LOG_LEVEL = "info"


# =============================================================================
# Whisper transcribe defaults (passed to WhisperModel.transcribe)
# =============================================================================

# Beam search width. Higher = better quality, slower. 10 is generous;
# turbo/distill models often work fine at 5.
BEAM_SIZE = 10
BEST_OF = 5

# Use the bundled Silero VAD to skip non-speech audio. Cuts wall time on
# files with long silences; rarely worth disabling.
VAD_FILTER = True

# Silero VAD parameters. The library defaults (min_silence_duration_ms=2000,
# speech_pad_ms=400) are tuned for long-form audio and EAT short dictation
# clips — a 2-3 s utterance with brief leading/trailing silence collapses to
# zero segments. The values below work for both short clips and long-form;
# tighten further (250 / 100) for very short clips.
VAD_MIN_SILENCE_MS: int = 500
VAD_SPEECH_PAD_MS: int = 200
VAD_THRESHOLD: float = 0.5

# Pass each segment's text into the prompt context for the next segment.
# Improves consistency on long-form audio; adds a tiny amount of latency.
# WARNING: many German finetunes (primeline-derived: tnfru, GalaktischeGurke,
# conkhidan) collapse to repeated punctuation when this is True. Set False if
# your selected model's card says so.
CONDITION_ON_PREVIOUS_TEXT = True

# Compute word-level timestamps via DTW alignment. Required for the
# `timestamp_granularities=["word"]` API option but EXPENSIVE and known to
# break certain finetunes (faster-whisper#1212): finetuned Whisper models
# can produce negative DTW timestamps which faster-whisper silently drops,
# leaving you with 0 segments. Set to False to disable word-level DTW for
# all requests — segment-level timestamps still work. Note: this takes
# precedence over the per-request `timestamp_granularities` field.
WORD_TIMESTAMPS_ENABLED = True

# Quality-check thresholds passed straight to model.transcribe(). Whisper
# drops a segment when:
#   no_speech_prob > NO_SPEECH_THRESHOLD  AND  avg_logprob < LOG_PROB_THRESHOLD
# OR when the segment text's gzip ratio exceeds COMPRESSION_RATIO_THRESHOLD.
# Finetunes can shift the no_speech distribution enough that these checks
# drop all real speech ("0 segments" symptom). When VAD_FILTER is True,
# faster-whisper Discussion #349 recommends setting all three to None so
# the VAD is the only gate. Use None to disable a check.
NO_SPEECH_THRESHOLD: "float | None" = 0.6
LOG_PROB_THRESHOLD: "float | None" = -1.0
COMPRESSION_RATIO_THRESHOLD: "float | None" = 2.4


# =============================================================================
# Whisper transcribe defaults — advanced (most users keep defaults)
# =============================================================================

# Persistent vocabulary biasing. Re-injected into the prompt of every decoder
# window — distinct from DEFAULT_PROMPT (which fades as decoded text
# accumulates). Useful for domain terms, drug names, person names. Ignored
# when prefix is set per-call.
DEFAULT_HOTWORDS: "str | None" = None

# Temperature fallback ladder (comma-separated floats). The decoder retries
# at each temperature when compression / log-prob checks fail. Ship the
# faster-whisper / OpenAI Whisper standard ladder explicitly so the admin UI's
# "Reset to default" gives users the safety net (a single value disables the
# fallback ladder and lets hallucination loops slip through). Empty = library
# default (currently identical, but explicit is safer for surprises).
TEMPERATURE: "str | None" = "0.0,0.2,0.4,0.6,0.8,1.0"

# Beam search patience; >1 keeps the beam alive longer. Default 1.0.
PATIENCE: float = 1.0

# Beam scoring length-norm exponent. >1 favors longer outputs. Default 1.0.
LENGTH_PENALTY: float = 1.0

# Multiplies logit of already-emitted tokens by 1/penalty. >1 discourages
# repetition loops. Default 1.0 (off). Try 1.05–1.2 for stutter audio.
REPETITION_PENALTY: float = 1.0

# Hard ban on n-grams of this size repeating. 0 = off.
NO_REPEAT_NGRAM_SIZE: int = 0

# Drop the running text prompt when temperature ladder fallback exceeds this
# value. Default 0.5. Only relevant when CONDITION_ON_PREVIOUS_TEXT=True.
PROMPT_RESET_ON_TEMPERATURE: float = 0.5


# =============================================================================
# Language detection (active when DEFAULT_LANGUAGE is empty)
# =============================================================================

# Re-detect language on every segment instead of only the first.
MULTILINGUAL: bool = False

# Min probability for the top language token to be accepted.
LANGUAGE_DETECTION_THRESHOLD: float = 0.5

# How many leading 30 s chunks to sample for language detection.
LANGUAGE_DETECTION_SEGMENTS: int = 1


# =============================================================================
# Anti-hallucination & token control
# =============================================================================

# With WORD_TIMESTAMPS_ENABLED, skip silent stretches longer than this many
# seconds when a possible hallucination is suspected. None = disabled.
HALLUCINATION_SILENCE_THRESHOLD: "float | None" = None

# Suppress blank token at start of decoder sampling. Default True. Almost
# never disable; only useful when debugging tokenizer behavior.
SUPPRESS_BLANK: bool = True

# Comma-separated token IDs to ban from output. "-1" = expand to model's
# default non-speech set; "" = no suppression.
SUPPRESS_TOKENS: "str | None" = "-1"

# Single chars to hard-mask via the loaded model's tokenizer. Resolved at
# request time to vocab IDs and merged into the effective suppress_tokens
# list. Empty / None = no extra suppression. Set to ".,?!:;" for verbatim
# dictation: model can't auto-insert punctuation, so spoken "Punkt" /
# "Komma" surface as words for the dictation-map PIPELINE_RULE to convert.
SUPPRESS_CHARS: "str | None" = None

# With WORD_TIMESTAMPS_ENABLED, glue these characters onto the FOLLOWING /
# PRECEDING word's timing. Locale-specific.
PREPEND_PUNCTUATIONS: str = "\"'“¿([{-"
APPEND_PUNCTUATIONS: str = "\"'.。,，!！?？:：”)]}、"


# =============================================================================
# Output wrappers — backend-level, NOT a faster-whisper param
# =============================================================================
# Plain strings prepended/appended to the final transcript text after the
# post-processing pipeline runs (before the final whitespace trim). Use to
# tag transcripts with model-specific banners, e.g.:
#   OUTPUT_PREFIX = "[de] "
#   OUTPUT_SUFFIX = " (errors possible)"
# Per-model overrides via MODEL_OVERRIDES win.
OUTPUT_PREFIX: str = ""
OUTPUT_SUFFIX: str = ""


# =============================================================================
# Load-time, hardware (advanced)
# =============================================================================

# Directory where HuggingFace model snapshots are cached. None = standard
# HF cache dir (~/.cache/huggingface).
DOWNLOAD_ROOT: "str | None" = None

# If True, never hit the network — only resolve from local cache.
LOCAL_FILES_ONLY: bool = False

# HuggingFace auth token for gated/private repos. None = no token.
USE_AUTH_TOKEN: "str | None" = None

# Auto-convert HuggingFace transformers Whisper models to CTranslate2 format
# on first load (when no model.bin is present). Requires
# `pip install -r requirements-convert.txt`.
AUTO_CONVERT_HF_MODELS: bool = False

# On-disk weight quantisation for auto-conversion. Independent of
# MODEL_COMPUTE_TYPE; CT2 up/down-casts at load.
CONVERT_QUANTIZATION: str = "float16"

# Output root for auto-converted CT2 models. None = ~/.cache/whisper-ct2.
CONVERTED_MODELS_DIR: "str | None" = None

# CPU threads for inference. 0 = library default (typically 4).
CPU_THREADS: int = 0

# Replicates the model so concurrent transcribe() calls run in true parallel.
# Costs ~Nx VRAM for activation buffers (weights are shared).
NUM_WORKERS: int = 1

# GPU index to bind to. 0 = first CUDA device.
DEVICE_INDEX: int = 0


# =============================================================================
# Per-model overrides (MODEL_OVERRIDES)
# =============================================================================
# Map of model_id -> dict of override fields. Each override may set any
# per-model-overrideable field; absent fields inherit the global default.
# Edited via the per-model pane of the admin UI; persisted in
# config.local.json. Env-var convention to pin per-model fields:
#   WHISPER_MODEL_OVERRIDE__<encoded_id>__<FIELD>
# where <encoded_id> URL-encodes "/" as "__SLASH__" and "." as "__DOT__".
MODEL_OVERRIDES: "dict[str, dict[str, object]]" = {}


# =============================================================================
# Admin WebUI (optional /settings browser editor)
# =============================================================================
# Off → /settings endpoints aren't registered at all. Auth on the endpoints
# themselves is per-user API key (see API_KEYS_DB below). With no admin key
# configured the server runs in OPEN mode and warns prominently in the UI
# and logs.
ADMIN_UI_ENABLED = True

# Allowlist of IPs / CIDRs allowed to reach admin endpoints — kept as a
# defense-in-depth layer alongside the API key. Loopback (127.0.0.1, ::1)
# is ALWAYS implicitly allowed.
ADMIN_ALLOWED_HOSTS: "list[str]" = ["127.0.0.1", "::1"]

# Same for /stats. Default loopback-only.
STATS_ALLOWED_HOSTS: "list[str]" = ["127.0.0.1", "::1"]


# =============================================================================
# Browser sessions (HttpOnly cookie auth for the WebUI)
# =============================================================================
# The WebUI exchanges a pasted API key at /auth/login for an HttpOnly session
# cookie (server-side store in SESSIONS_DB). Non-browser clients (Vowen, curl)
# keep using `Authorization: Bearer` and never touch any of this.

# Mark the session/CSRF cookies `Secure` (browser only sends them over HTTPS).
# Default OFF so plain-HTTP LAN/VPN access works. Set True on any instance
# served over HTTPS (e.g. behind a TLS-terminating reverse proxy), otherwise
# the cookie is set but never sent back and login silently fails.
SESSION_COOKIE_SECURE = False

# Sliding session lifetime in seconds. Each authenticated request refreshes
# the expiry (debounced). Idle longer than this → re-login. Default 30 days.
SESSION_TTL_SECONDS = 2_592_000

# Cookie names. Session cookie is HttpOnly (JS cannot read it); the CSRF
# cookie is readable by JS so the client can echo it back as X-CSRF-Token.
SESSION_COOKIE_NAME = "whisper_session"
SESSION_CSRF_COOKIE_NAME = "whisper_csrf"


# =============================================================================
# Transcription error reports
# =============================================================================
# Users can flag a wrong transcription from /quick-config; admins triage on
# /reports. The store is durable PHI: plaintext SQLite next to
# config.local.json. Whole-disk encryption is the deployment's responsibility.

# DB file path. Default sits next to config.local.json. SQLite uses three
# files at runtime (.sqlite3, -wal, -shm); .gitignore matches all three.
REPORTS_DB = os.path.join(_REPO_DIR, "reports.local.sqlite3")

# Soft cap. On overflow upsert_report() evicts oldest closed reports first
# (resolved/dismissed), then oldest open. Tune lower for memory-tight LAN
# deployments; the admin page is client-side filtered so the practical
# upper bound is around what a browser can render in one DOM.
REPORTS_MAX = 1000

# Auto-delete reports older than this many days. Sweep runs on startup and
# hourly thereafter. Set to 0 to disable (admin must clear manually).
REPORTS_RETENTION_DAYS = 90

# Master switch for end-user report submission. Set to False to make
# /quick-config/reports/api/submit return 403 for everyone except admins.
# The button stays visible but submission is rejected.
REPORTS_ALLOW_USER_SUBMIT = True


# =============================================================================
# Recent transcriptions (persistent /quick-config trace panel + /stats widget)
# =============================================================================
# Every /transcribe request UPSERTs a row into the recent-transcriptions
# SQLite store. The store backs both the /quick-config trace panel
# (full payload: raw/final/steps/tokens/bigrams) and the /stats dashboard
# "Recent transcriptions" widget (timing-only projection). Survives
# service restart; pruned lazily by row-cap AND TTL.

# DB file path. Default sits next to config.local.json. SQLite uses three
# runtime files (.sqlite3, -wal, -shm); .gitignore matches all three.
RECENT_TRANSCRIPTIONS_DB = os.path.join(_REPO_DIR, "recent_transcriptions.local.sqlite3")

# Hard row-count cap. 0 = unbounded (TTL-only pruning). Lazy pruning runs
# every RECENT_TRANSCRIPTIONS_PRUNE_EVERY inserts, so the actual on-disk
# row count may briefly exceed this by up to PRUNE_EVERY entries before
# the next sweep. 500 is the documented default — keeps the UI useful
# without ballooning the DB when traces are large.
RECENT_TRANSCRIPTIONS_MAX = 500

# Auto-delete entries older than this many days. 0 = disabled
# (count-cap only). Combined with the row cap: whichever bound is tighter
# wins.
RECENT_TRANSCRIPTIONS_TTL_DAYS = 30

# Number of entries the browser fetches per page. The freshest page is
# delivered via SSE on connect; "Load older" walks back through the store
# in batches of this size using the created_ts cursor. Also clamps the
# server-side LIMIT, so a hostile client can't request a huge page.
RECENT_TRANSCRIPTIONS_PAGE_SIZE = 100

# Lazy-prune cadence — every Nth insert runs a single DELETE that
# enforces both the row cap and the TTL. 0 disables lazy pruning (rows
# accumulate until a manual /clear or service restart sweep). 50 is the
# documented default.
RECENT_TRANSCRIPTIONS_PRUNE_EVERY = 50

# /stats "Recent transcriptions" widget row count. The dashboard is
# intentionally a small ticker — bumping this past ~50 makes the widget
# scroll badly without adding value.
STATS_RECENT_TX_DISPLAY = 20


# =============================================================================
# Per-key / per-user usage rollup
# =============================================================================
# Durable hourly rollup (one row per key per UTC hour) backing the per-user/
# per-key usage numbers on /api-keys, the usage-over-time section on /stats, and
# the per-user "today" banner on /quick-config. Hourly UTC buckets let "today"
# be reckoned in any timezone (the viewer's for the banner, the server's for the
# dashboards). Kept separate from RECENT_TRANSCRIPTIONS because that store prunes
# to a rolling window and so can't back lifetime totals. See usage_store.py.

# DB file path. Default sits next to config.local.json. SQLite uses three
# runtime files (.sqlite3, -wal, -shm); .gitignore matches all three.
USAGE_DB = os.path.join(_REPO_DIR, "usage.local.sqlite3")

# Auto-delete rollup rows older than this many days. 0 = unbounded (the
# default): the rollup is at most one row per active key per hour, so it
# stays tiny and lifetime totals stay complete. Set >0 only if you want a
# bounded retention window.
USAGE_RETENTION_DAYS = 0


# =============================================================================
# API key auth (multi-user identity)
# =============================================================================
# Per-user API keys gate /v1/audio/transcriptions and every WebUI endpoint.
# Storage: SQLite at API_KEYS_DB; hashed with SHA-256. See api_keys_store.py.
#
# Bootstrap: if no active admin key exists in the DB, the server starts in
# OPEN mode — every request is accepted as a synthetic admin — and emits a
# WARNING every 60 s plus a red banner on every WebUI page. The operator
# creates the first admin user/key in /settings/api-keys.
#
# Optional shortcut: setting WHISPER_BOOTSTRAP_ADMIN_KEY at startup creates
# (if needed) a `bootstrap-admin` user holding that exact key, so the
# operator can paste it into Vowen / curl immediately. The variable is read
# once and never persisted in plaintext; only the SHA-256 hash hits disk.

API_KEYS_DB = os.path.join(_REPO_DIR, "api_keys.local.sqlite3")

# Durable browser-session store (SQLite, WAL). Maps an opaque session token
# to a user_id (+ per-session CSRF token + sliding expiry). Sits next to
# config.local.json; .gitignore matches the *.local.sqlite3* triple.
SESSIONS_DB = os.path.join(_REPO_DIR, "sessions.local.sqlite3")

# If set, on startup we insert (or no-op) a user named `bootstrap-admin`
# with this exact raw key. NEVER stored in config.local.json. Operator
# typically sets it once, copies the value into their client, then unsets
# the env var (the key is independently stored in the DB).
BOOTSTRAP_ADMIN_KEY: "str | None" = None


# =============================================================================
# Whisper fine-tuning capture store
# =============================================================================
# Optional pipeline that persists the original audio + word-level timestamps
# next to the model's raw/final transcription so an admin can review each
# clip karaoke-style on /captures and produce ground-truth text for Whisper
# fine-tuning. Default OFF — audio is biometric-grade PHI; the master
# switch demands an explicit opt-in.
#
# Storage layout:
#   CAPTURES_DB  — SQLite (WAL), metadata + word timestamps + corrections
#   CAPTURES_DIR — filesystem root for audio (4-char fanout subdirs)
#
# Export endpoint streams a tar.gz containing manifest.jsonl + audio/<id>.<ext>,
# loadable via huggingface `datasets.load_dataset('json', data_files=...)`.

# Master switch — when False, the transcribe handler never copies audio
# and never inserts a capture row. Browsing /captures still works
# (existing rows visible).
CAPTURE_RECORDINGS_ENABLED = False

CAPTURES_DB = os.path.join(_REPO_DIR, "captures.local.sqlite3")
CAPTURES_DIR = os.path.join(_REPO_DIR, "captures")

# Soft caps. On overflow, _evict_to_cap drops rows in priority order:
# dismissed → audio_missing → reviewed → new → ready. Training-quality
# ("ready") wins; unreviewed work ("new") is also protected.
CAPTURES_MAX = 5000
CAPTURES_MAX_MB = 5000

# Auto-delete captures older than this many days. Sweep runs on startup
# and hourly thereafter. 0 = disabled.
CAPTURES_RETENTION_DAYS = 365

# Sampling: 1.0 captures every eligible request, 0.1 captures ~10% etc.
# Decision is made per-request before transcribe runs.
CAPTURE_RECORDINGS_SAMPLE_RATE = 1.0

# Duration filter — too-short clips are usually false starts, too-long
# ones strain memory and need re-segmentation before fine-tuning anyway.
# Min default 1.0 s: below ~1 s of speech a clip is mostly the 30 s zero-pad
# Whisper applies, carrying little training signal (the conventional ASR
# floor; LibriSpeech bottoms out near 1 s). This is the RAW ingestion gate;
# the finished-sample floor is CAPTURES_SAMPLE_MIN_DURATION_S below.
CAPTURE_RECORDINGS_MIN_DURATION_SEC = 1.0
CAPTURE_RECORDINGS_MAX_DURATION_SEC = 600.0

# Pre-transcribe size guard: skip eligibility roll for uploads larger
# than this many bytes. Keeps a misbehaving client from filling the
# captures dir with multi-100MB blobs.
CAPTURE_RECORDINGS_AUDIO_BYTES_HARD_LIMIT = 100_000_000


# Sample sizing — global bounds on a finished training sample (a packed
# capture_samples row OR a single-capture sample). All measured on the
# TRIMMED+spaced merged audio, not raw. These are the single source of
# truth for the merge/preview/proposer paths (no per-merge overrides).
#   MIN — finished-sample floor; just discards near-empty junk (the proposer
#         packs the bulk toward TARGET so this only bites tiny solos).
#   MAX — hard ceiling. Whisper truncates >30 s; keep a margin. The merge,
#         the 28 s validation, the merge-estimate, and the proposer all read
#         this one value (was four hardcoded 28 s sites).
#   JOIN_STRATEGY — how member transcripts concatenate ("space" or
#         "period_space"); applies to every new/regenerated sample.
# Constraint (enforced in config_store): MIN <= PROPOSER_TARGET_S <= MAX < 30.
CAPTURES_SAMPLE_MIN_DURATION_S = 1.0
CAPTURES_SAMPLE_MAX_DURATION_S = 29.9
CAPTURES_SAMPLE_JOIN_STRATEGY = "space"


# ---------------------------------------------------------------------
# Captures-specific pipeline rule exclusion
# ---------------------------------------------------------------------
# /transcribe runs PIPELINE_RULES → produces `final` (the runtime
# response). The captures pipeline runs the SAME rules minus this
# exclude set → produces `text_for_training` (the column the export
# manifest reads).
#
# Default skip-set produces word-form training text that matches
# Whisper's raw output at inference time under SUPPRESS_CHARS:
#   - `dictation-map`: converts spoken "Komma"/"Punkt"/"Klammer auf"
#     into ","/"."/"(" etc. Keeping the WORDS in training text avoids
#     teaching the model to emit tokens it will then be suppressed
#     from at inference.
#   - `capitalize-after-terminator`: depends on terminators (.?!)
#     existing — with dictation-map skipped, there are no terminators,
#     so the rule would partial-fire only on `\n`. Cleaner to skip
#     entirely; the training text matches raw Whisper casing exactly.
#
# All other rules (ß→ss, ẞ→SS, digit-range normalisation, dedup-space,
# edge-trim, etc.) continue to run — those are general-correction
# rules that improve training data quality without changing the
# punctuation distribution.
CAPTURES_PIPELINE_RULES_EXCLUDE: "set[str]" = {
    "dictation-map",
    "capitalize-after-terminator",
}


# ---------------------------------------------------------------------
# Captures-specific silence trimming (Silero VAD)
# ---------------------------------------------------------------------
# Separate from the transcription-side VAD knobs (cfg.VAD_FILTER etc.)
# because the concerns differ: transcription VAD affects what Whisper
# hears for the inference response; captures VAD trims the stored audio
# so reviewers see — and the fine-tune learns from — clips without
# excessive leading/trailing silence (Calm-Whisper arXiv:2505.12969
# documents silence-induced hallucination as a fine-tune failure mode).
#
# Auto-trim runs after merge_wavs() produces a sample's merged WAV. (The old
# manual per-singleton "Trim silence" button was retired — a single capture is
# trimmed by turning it into a one-member sample, same uniform model.)
CAPTURES_VAD_TRIM_ENABLED_FOR_GROUPS = True
# Per-member group trim (CAPTURES_VAD_TRIM_ENABLED_FOR_GROUPS path): silence is
# now trimmed from EVERY member before concatenation, not just the merged WAV's
# outer edges. Without this, member i's trailing + the inter-segment gap +
# member i+1's leading silence stacked into multi-second dead air at each join —
# bad fine-tune data (silence-induced hallucination, wasted 30 s window).
#   GROUP_EDGE_MS     — silence kept on each member's outer edges (margin so
#                       tight VAD boundaries don't clip word onsets).
#   GROUP_INTERNAL_MS — internal silences inside a member are capped at this
#                       (matches the inter-segment gap → uniform silence).
CAPTURES_VAD_MARGIN_GROUP_EDGE_MS = 300
CAPTURES_VAD_MARGIN_GROUP_INTERNAL_MS = 300


# Auto-merge proposer (/captures "Auto-propose merges" panel) ---------------
#
# Heuristic ranks groupings of ungrouped captures into ~26-second training
# samples honoring the existing 28 s hard cap. Knobs:
#   SESSION_GAP_S    — captures more than this many seconds apart start a
#                      new session bucket (tractability + density score).
#   DUP_THRESHOLD    — difflib.ratio above this rejects pairing in a group
#                      (near-duplicate redictation / echo guard).
#   MAX_PROPOSALS    — cap on returned proposals per request.
#   TARGET_S         — fill-score peak; should sit 1+ s below the sample-max
#                      cliff so the proposer doesn't camp at the rejection edge.
#   CACHE_TTL_S      — proposer result TTL; invalidated on capture writes.
# (Per-capture min length is governed by CAPTURE_RECORDINGS_MIN_DURATION_SEC;
# the finished-sample floor by CAPTURES_SAMPLE_MIN_DURATION_S.)
CAPTURES_PROPOSER_SESSION_GAP_S = 600
CAPTURES_PROPOSER_DUP_THRESHOLD = 0.85
CAPTURES_PROPOSER_MAX_PROPOSALS = 20
CAPTURES_PROPOSER_TARGET_S = 26.0
CAPTURES_PROPOSER_CACHE_TTL_S = 60


# Snapshot the in-file defaults BEFORE config.local.json + env overrides apply.
# Used by main.py's request log block to mark non-default scalar values with
# `*` so the operator can see at a glance which knobs are overridden — and
# by the admin UI's "↺ Reset" button to recover the in-repo default. Deep-copy
# because the env-override block below mutates MODEL_OVERRIDES IN PLACE via
# setdefault(); a shallow snapshot would keep the same dict reference and the
# "default" handed to the WebUI would silently carry env-injected overrides.
import copy as _copy
_BASELINE: "dict[str, object]" = _copy.deepcopy({
    k: v for k, v in globals().items()
    if k.isupper() and not k.startswith("_")
})
del _copy


# =============================================================================
# Runtime overrides from config.local.json (admin WebUI)
# =============================================================================
# Loaded between in-file defaults and env-var overrides so precedence is:
#     ENV var  >  config.local.json  >  in-file default (above)
# Failure to load NEVER raises — see config_store.load_overrides for details.
try:
    from config_store import load_overrides as _load_overrides

    for _k, _v in _load_overrides().items():
        globals()[_k] = _v
except ImportError:
    # config_store depends on pydantic; if it isn't installed we still want
    # config.py to import cleanly so the rest of the app can run.
    pass


# =============================================================================
# Environment variable overrides (deployment-time)
# =============================================================================
# Anything below here lets the env var win over the in-file default. Touch
# only if you want to change the override syntax itself.

# Collects "couldn't parse WHISPER_X=..." messages encountered while applying
# env overrides at import time. main.py drains this AFTER logging is configured
# (config.py runs too early to log), so a typo like WHISPER_BEAM_SIZE=ten is
# surfaced as a warning rather than silently ignored. See main.py startup.
_ENV_WARNINGS: list[str] = []

def _truthy(s: str) -> bool:
    return s.strip().lower() in ("1", "true", "yes", "on")

def _env_int(name: str, current: int) -> int:
    raw = os.environ.get(name)
    if raw is None or not raw.strip():
        return current
    try:
        return int(raw)
    except ValueError:
        _ENV_WARNINGS.append(f"{name}={raw!r} is not a valid integer; keeping {current!r}")
        return current

def _env_float(name: str, current: float) -> float:
    raw = os.environ.get(name)
    if raw is None or not raw.strip():
        return current
    try:
        return float(raw)
    except ValueError:
        _ENV_WARNINGS.append(f"{name}={raw!r} is not a valid number; keeping {current!r}")
        return current

def _env_float_or_none(name: str, current: "float | None") -> "float | None":
    """Like _env_float but an explicit empty string means None (disable)."""
    raw = os.environ.get(name)
    if raw is None:
        return current
    if not raw.strip():
        return None
    try:
        return float(raw)
    except ValueError:
        _ENV_WARNINGS.append(f"{name}={raw!r} is not a valid number; keeping {current!r}")
        return current

def _env_bool(name: str, current: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None or not raw.strip():
        return current
    return _truthy(raw)

def _env_str(name: str, current: str) -> str:
    """Stripped-string env passthrough — empty / unset → keep current."""
    raw = os.environ.get(name)
    return raw.strip() if raw and raw.strip() else current

def _env_str_or_none(name: str, current: "str | None") -> "str | None":
    """Env override where explicit empty string means "disable" (→ None).
    Unset env → keep current."""
    raw = os.environ.get(name)
    return (raw or None) if raw is not None else current

def _env_str_passthrough(name: str, current: str) -> str:
    """Raw-string env override — empty string is preserved as a real value."""
    raw = os.environ.get(name)
    return raw if raw is not None else current

def _env_csv_list(name: str, current: list[str]) -> list[str]:
    """Comma-separated list parse — unset → keep current; explicitly-empty
    env (e.g. WHISPER_PRELOAD_MODELS="") → empty list. Callers that need
    "empty → keep current" wrap the result with `or current`."""
    raw = os.environ.get(name)
    if raw is None:
        return current
    return [s.strip() for s in raw.split(",") if s.strip()]

# --- Secrets: *_FILE indirection -------------------------------------------
# For sensitive values, allow `WHISPER_<NAME>_FILE=/path` (Docker/K8s secrets,
# kept out of `docker inspect` / /proc/<pid>/environ). If the *_FILE form is set
# and the plain var is not, read+strip the file into os.environ so the normal
# readers below (and the per-model loop) pick it up uniformly.
for _secret in ("WHISPER_BOOTSTRAP_ADMIN_KEY", "WHISPER_USE_AUTH_TOKEN"):
    _path = os.environ.get(_secret + "_FILE")
    if _path and not os.environ.get(_secret):
        try:
            with open(_path, encoding="utf-8") as _fh:
                os.environ[_secret] = _fh.read().strip()
        except OSError as _exc:
            _ENV_WARNINGS.append(f"{_secret}_FILE={_path!r} could not be read: {_exc}")


# --- Non-AdminConfig constants (no WebUI row → not in ENV_VAR_MAPPING) -------
ADMIN_UI_ENABLED = _env_bool("WHISPER_ADMIN_UI", ADMIN_UI_ENABLED)
API_KEYS_DB = _env_str("WHISPER_API_KEYS_DB", API_KEYS_DB)
SESSIONS_DB = _env_str("WHISPER_SESSIONS_DB", SESSIONS_DB)
BOOTSTRAP_ADMIN_KEY = _env_str("WHISPER_BOOTSTRAP_ADMIN_KEY", BOOTSTRAP_ADMIN_KEY)
USAGE_DB = _env_str("WHISPER_USAGE_DB", USAGE_DB)
USAGE_RETENTION_DAYS = _env_int("WHISPER_USAGE_RETENTION_DAYS", USAGE_RETENTION_DAYS)
CAPTURES_PROPOSER_SESSION_GAP_S = _env_int(
    "WHISPER_CAPTURES_PROPOSER_SESSION_GAP_S", CAPTURES_PROPOSER_SESSION_GAP_S)
CAPTURES_PROPOSER_DUP_THRESHOLD = _env_float(
    "WHISPER_CAPTURES_PROPOSER_DUP_THRESHOLD", CAPTURES_PROPOSER_DUP_THRESHOLD)
CAPTURES_PROPOSER_MAX_PROPOSALS = _env_int(
    "WHISPER_CAPTURES_PROPOSER_MAX_PROPOSALS", CAPTURES_PROPOSER_MAX_PROPOSALS)
CAPTURES_PROPOSER_TARGET_S = _env_float(
    "WHISPER_CAPTURES_PROPOSER_TARGET_S", CAPTURES_PROPOSER_TARGET_S)
CAPTURES_PROPOSER_CACHE_TTL_S = _env_int(
    "WHISPER_CAPTURES_PROPOSER_CACHE_TTL_S", CAPTURES_PROPOSER_CACHE_TTL_S)
CAPTURES_SAMPLE_MIN_DURATION_S = _env_float(
    "WHISPER_CAPTURES_SAMPLE_MIN_DURATION_S", CAPTURES_SAMPLE_MIN_DURATION_S)
CAPTURES_SAMPLE_MAX_DURATION_S = _env_float(
    "WHISPER_CAPTURES_SAMPLE_MAX_DURATION_S", CAPTURES_SAMPLE_MAX_DURATION_S)
CAPTURES_SAMPLE_JOIN_STRATEGY = _env_str(
    "WHISPER_CAPTURES_SAMPLE_JOIN_STRATEGY", CAPTURES_SAMPLE_JOIN_STRATEGY)


# --- Schema-driven env application for every AdminConfig field ---------------
# ENV_VAR_MAPPING (config_store.py) is the single source of truth for which
# AdminConfig field maps to which WHISPER_* var; the WebUI badges / greys out a
# field iff its var is set. Here we apply each mapped var to the matching module
# constant, coercing by the field's pydantic annotation so a new field becomes
# env-configurable automatically (a test asserts the mapping stays complete).
#
# A few fields need bespoke handling and are skipped by the generic loop:
#   _ENV_SPECIAL_CASES — set/list-with-keep-current / custom-default semantics
#   _ENV_JSON_FIELDS    — structured values supplied as a JSON string
# and a handful of string fields override the default empty-string behaviour
# (the generic default for str is "empty → keep current").
_ENV_SPECIAL_CASES = {
    "ALLOWED_MODELS", "ADMIN_ALLOWED_HOSTS", "STATS_ALLOWED_HOSTS",
    "CAPTURES_PIPELINE_RULES_EXCLUDE", "CONVERT_QUANTIZATION",
}
_ENV_JSON_FIELDS = {"PIPELINE_RULES", "MODEL_OVERRIDES"}
_ENV_READER_OVERRIDES = {
    # empty string CLEARS the value to None (disable the feature)
    "DEFAULT_PROMPT": "str_or_none", "DEFAULT_HOTWORDS": "str_or_none",
    "TEMPERATURE": "str_or_none", "SUPPRESS_TOKENS": "str_or_none",
    "SUPPRESS_CHARS": "str_or_none", "DOWNLOAD_ROOT": "str_or_none",
    "USE_AUTH_TOKEN": "str_or_none", "CONVERTED_MODELS_DIR": "str_or_none",
    # empty string is PRESERVED as a literal value (e.g. "" prefix/suffix, or
    # DEFAULT_LANGUAGE="" meaning auto-detect)
    "DEFAULT_MODEL": "passthrough", "LOG_FILE": "passthrough",
    "PREPEND_PUNCTUATIONS": "passthrough", "APPEND_PUNCTUATIONS": "passthrough",
    "OUTPUT_PREFIX": "passthrough", "OUTPUT_SUFFIX": "passthrough",
    "DEFAULT_LANGUAGE": "passthrough",
    # Optional thresholds where an empty string disables the check (→ None)
    "NO_SPEECH_THRESHOLD": "float_or_none", "LOG_PROB_THRESHOLD": "float_or_none",
    "COMPRESSION_RATIO_THRESHOLD": "float_or_none",
    "HALLUCINATION_SILENCE_THRESHOLD": "float_or_none",
}
_ENV_READER_FUNCS = {
    "int": _env_int, "float": _env_float, "float_or_none": _env_float_or_none,
    "bool": _env_bool, "str": _env_str, "str_or_none": _env_str_or_none,
    "passthrough": _env_str_passthrough, "csv_list": _env_csv_list,
}


def _env_reader_kind(field: str, current) -> str:
    """Pick the reader for a field. Explicit overrides win; otherwise infer
    from the current (post-local.json) value's Python type so a newly added
    field is handled without touching this file."""
    if field in _ENV_READER_OVERRIDES:
        return _ENV_READER_OVERRIDES[field]
    if isinstance(current, bool):  # bool before int (bool is an int subclass)
        return "bool"
    if isinstance(current, int):
        return "int"
    if isinstance(current, float):
        return "float"
    if isinstance(current, (list, set, frozenset)):
        return "csv_list"
    if current is None:
        return "str_or_none"
    return "str"  # plain string: empty → keep current (safe default)


try:
    from config_store import AdminConfig as _AdminConfig
    from config_store import ENV_VAR_MAPPING as _ENV_VAR_MAPPING

    for _field, _env in _ENV_VAR_MAPPING.items():
        if _field in _ENV_SPECIAL_CASES or _field in _ENV_JSON_FIELDS:
            continue
        _cur = globals()[_field]
        globals()[_field] = _ENV_READER_FUNCS[_env_reader_kind(_field, _cur)](_env, _cur)

    # --- JSON-encoded structured fields (escape hatch) ----------------------
    for _field in _ENV_JSON_FIELDS:
        _raw = os.environ.get(_ENV_VAR_MAPPING[_field])
        if _raw is None or not _raw.strip():
            continue
        try:
            _parsed = json.loads(_raw)
            # Validate then dump back to plain dicts/lists so the runtime shape
            # matches config.local.json (load_overrides uses the same dump).
            _validated = _AdminConfig.model_validate({_field: _parsed})
            globals()[_field] = _validated.model_dump(exclude_none=True)[_field]
        except Exception as _exc:  # noqa: BLE001 — never fail import over bad env
            _ENV_WARNINGS.append(
                f"{_ENV_VAR_MAPPING[_field]} is not valid JSON for {_field}: {_exc}")
except ImportError:
    # pydantic / config_store unavailable — fall back to bare in-file defaults.
    pass


# --- Special-case readers (preserve exact legacy semantics) -----------------
# ALLOWED_MODELS: CSV → set; explicit "" means an empty set ("any model passes").
_env_allowed = os.environ.get("WHISPER_ALLOWED_MODELS")
if _env_allowed is not None:
    ALLOWED_MODELS = {s.strip() for s in _env_allowed.split(",") if s.strip()}

# CAPTURES_PIPELINE_RULES_EXCLUDE is stored/used as a set of rule slugs.
_env_cap_excl = os.environ.get("WHISPER_CAPTURES_PIPELINE_RULES_EXCLUDE")
if _env_cap_excl is not None:
    CAPTURES_PIPELINE_RULES_EXCLUDE = {
        s.strip() for s in _env_cap_excl.split(",") if s.strip()}

# Allowlists: empty string is treated as "no override" (keep in-file/local.json)
# so the loopback-only default can't be wiped by an empty env var.
ADMIN_ALLOWED_HOSTS = _env_csv_list("WHISPER_ADMIN_ALLOWED_HOSTS", ADMIN_ALLOWED_HOSTS) or ADMIN_ALLOWED_HOSTS
STATS_ALLOWED_HOSTS = _env_csv_list("WHISPER_STATS_ALLOWED_HOSTS", STATS_ALLOWED_HOSTS) or STATS_ALLOWED_HOSTS

# CONVERT_QUANTIZATION: explicit "" falls back to the library default float16.
_env_convert_quant = os.environ.get("WHISPER_CONVERT_QUANTIZATION")
if _env_convert_quant is not None:
    CONVERT_QUANTIZATION = _env_convert_quant or "float16"


# --- Per-model overrides via env (WHISPER_MODEL_OVERRIDE__<id>__<FIELD>) ----
# Convention: model id is encoded by replacing "/" with "__SLASH__" and "." with
# "__DOT__" so HF-style ids round-trip cleanly through env var names. Field
# names are UPPER_CASE matching the AdminConfig field. Values are parsed in
# the same way as their global counterparts (int, float, bool, string).
def _decode_model_id(s: str) -> str:
    return s.replace("__SLASH__", "/").replace("__DOT__", ".")


# Module-level field-type lookup for _coerce_override_value. Names track
# ModelOverride (config_store.py) — fields not in this class are pure
# string passthroughs (TEMPERATURE) or rejected by pydantic at save time.
_OVERRIDE_BOOL_FIELDS = frozenset({
    "CONDITION_ON_PREVIOUS_TEXT", "WORD_TIMESTAMPS_ENABLED",
    "VAD_FILTER", "MULTILINGUAL", "SUPPRESS_BLANK",
})
_OVERRIDE_INT_FIELDS = frozenset({
    "BEAM_SIZE", "BEST_OF", "VAD_MIN_SILENCE_MS", "VAD_SPEECH_PAD_MS",
    "NO_REPEAT_NGRAM_SIZE", "LANGUAGE_DETECTION_SEGMENTS",
    "NUM_WORKERS", "DEVICE_INDEX",
})
_OVERRIDE_FLOAT_FIELDS = frozenset({
    "VAD_THRESHOLD", "NO_SPEECH_THRESHOLD", "LOG_PROB_THRESHOLD",
    "COMPRESSION_RATIO_THRESHOLD", "PATIENCE", "LENGTH_PENALTY",
    "REPETITION_PENALTY", "PROMPT_RESET_ON_TEMPERATURE",
    "LANGUAGE_DETECTION_THRESHOLD", "HALLUCINATION_SILENCE_THRESHOLD",
})
_OVERRIDE_LIST_FIELDS = frozenset({
    "PIPELINE_RULES_EXCLUDE", "PIPELINE_RULES_INCLUDE",
})


def _coerce_override_value(field: str, raw: str) -> object:
    """Coerce a raw env-var string to the right type for a ModelOverride field.
    Falls back to the raw string for fields we can't easily classify (the
    pydantic validator will catch type mismatches at save-merge time)."""
    if field in _OVERRIDE_BOOL_FIELDS:
        return _truthy(raw)
    if field in _OVERRIDE_INT_FIELDS:
        try:
            return int(raw)
        except ValueError:
            return raw
    if field in _OVERRIDE_FLOAT_FIELDS:
        try:
            return float(raw)
        except ValueError:
            return raw
    if field in _OVERRIDE_LIST_FIELDS:
        return [s.strip() for s in raw.split(",") if s.strip()]
    return raw


_OVERRIDE_PREFIX = "WHISPER_MODEL_OVERRIDE__"
for _k, _v in os.environ.items():
    if not _k.startswith(_OVERRIDE_PREFIX):
        continue
    _rest = _k[len(_OVERRIDE_PREFIX):]
    # Split on the LAST "__<UPPER>" occurrence. We can't just split on "__"
    # because the encoded id contains "__SLASH__" and "__DOT__".
    # Strategy: find the last "__" that isn't part of __SLASH__/__DOT__ by
    # walking from the right.
    _idx = -1
    _i = len(_rest) - 1
    while _i >= 0:
        # find a "__" boundary
        _pos = _rest.rfind("__", 0, _i + 1)
        if _pos < 0:
            break
        # is it the boundary BEFORE __SLASH__ / __DOT__ / __FIELD__?
        # We're scanning right-to-left looking for the boundary that
        # separates the encoded id from the field name. Skip if the segment
        # to the right starts with one of our encoded markers.
        _tail = _rest[_pos + 2:]
        if _tail.startswith("SLASH__") or _tail.startswith("DOT__"):
            _i = _pos - 1
            continue
        _idx = _pos
        break
    if _idx <= 0:
        continue
    _enc_id = _rest[:_idx]
    _field = _rest[_idx + 2:]
    _model_id = _decode_model_id(_enc_id)
    _entry = MODEL_OVERRIDES.setdefault(_model_id, {})
    _entry[_field] = _coerce_override_value(_field, _v)
